---
# tasks file for roles/laptop_setup
- name: Add {{ sudo_user }} user
  user:
    name: "{{ sudo_user }}"
    groups: "{{ sudo_user }}"
    append: true
    password: "{{ password }}"
    state: present
    createhome: true

- name: Make sudo without password for {{ sudo_user }} user
  copy:
    dest: /etc/sudoers.d/sudo-manish
    content: "{{ sudo_user }} ALL=(ALL) NOPASSWD:ALL"
    mode: 0440

- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Install tools
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == 'Linux Mint'
  loop:
    - htop
    - wget
    - tree
    - git
    - vim
